### ISSUE TITLE
Website builder integration

### ISSUE THREAD

**Issue by NukeManDan** [cluster-labs/ipfscloud-web#15]
https://ipfscloud.store/app/build/ is a handy tool - I would think that integration (optionally) in a self-hosted instance of IPFSCloud would be valuable! 

- [x] Add the dependencies... these?
```html
<link rel="stylesheet" href="dist/grapesjs/grapes.min.css">
  | <link rel="stylesheet" href="dist/gramateria/gram.min.css">
```
- [ ] Add link in `host.html`
  - possibly to https://ipfscloud.store/app/build/  to start, then to local instance when ready

**Comment by vasa-develop** [comment]
Right now you can actually use https://ipfscloud.store/app/build/ locally by cloning the project(try production branch) and running it locally on localhost(using apache or any server).

**Comment by vasa-develop** [comment]
This will be added to **IpfsCloud v2.0**.

You can **get more details** about IpfsCloud v2.0 [**here**](https://discuss.ipfs.io/t/community-discussion-ipfscloud-v2-0-draft/5420)

Want to **Contribute** or **track our progress**? Head over [**here**](https://github.com/cluster-labs/grafia)
