### ISSUE TITLE
overwritten text on home page after logging in

### ISSUE THREAD

**Issue by jessepinkman9900** [cluster-labs/ipfscloud-web#21]
there is overwritten text in top left corner after logging into cloud account
screenshot below:
![Screenshot from 2019-05-11 21-04-51](https://user-images.githubusercontent.com/44177346/57571875-ed4cdb00-7430-11e9-95c6-f232b711171c.png)

**Comment by vasa-develop** [comment]
Seems like the logo is not loaded and thus the alternative text is messing up the UI.
Will look into that.

**Comment by vasa-develop** [comment]
Seems to wok now ;)

![screenshot](https://user-images.githubusercontent.com/28847087/57966047-6042de00-796a-11e9-9356-674ba3dfbd25.png)
